In [5]:
#why pyrhon?
#* python lists are very slow in performing complex mathematical operation so we use numpy

import numpy as np
arr = np.array([10,20,30])
print(arr)
print(np.__version__)

[10 20 30]
1.26.4


In [7]:
#printing the float
arr = np.array([10.2,13.5])
print(arr)

[10.2 13.5]


In [23]:
#lists v/s Numpy
lst = [10,30,40]
c = lst+2
print(c)

TypeError: can only concatenate list (not "int") to list

In [21]:
#by using the numpy we same as we did in the list
arr = (np.array([10,20,30]))# we will add 2 numbers
print(arr+2)

[12 22 32]


In [27]:
#Importance of numpy
#*numpy is helpful in createing an dimensional array.(2D,3D,4D...ND)
#*numpy is the backbone of remaining libraries like pandas,matplotlib,scikit etc
#*it will helpful in  the visualization
# numpy has vectorization features
#NEEDS OF NUMPY:
#*creation of array, it perform operations on those array
#integral calclas
#*swfferentail equations
#*statistical related operation
#difference b'w numpy and array
#*list is python builti type but numpy we have to install
#*list can store both homogeneous and heterogenous data but numpy only store homogeneous data
#*in list we can"t perform vector operations and numpy we can perform i n-demensional array
#*arrays condsume less memory than list
#*numpy arrays are more cionvinenr to use while performing multiple complex operations.

In [35]:
import numpy as np
import sys
lst = [10,20,30,40,50,60,70,80,90,100,200,300,400]
arr = np.array([10,20,30,40,50,60,70,80,90,100,200,300,400])
print(f"the size of the list:{sys.getsizeof(lst)} bytes")
print(f"the size of the array:{sys.getsizeof(arr)} bytes")
print(f"the size of the elements in the list:{sys.getsizeof(lst)+sum(i for i in lst)} bytes")
print(f"the size of the elements in the array:{sys.getsizeof(arr)+sum(i for i in arr)} bytes")

the size of the list:168 bytes
the size of the array:164 bytes
the size of the elements in the list:1618 bytes
the size of the elements in the array:1614 bytes


In [41]:
import time
size = 1000
a = list(range(size))
b = list(range(size))
def dotProduct(a,b):
    ans = 0
    for i,j in zip(a,b):
        ans+= i*j
    return ans
start = time.perf_counter()
for i in range(size):
    dotProduct(a,b)
end = time.perf_counter()
x = np.array(range(size))
y = np.array(range(size))
print(f"time took to do dot product using python list {end-start:.4f}")
start = time.perf_counter()
for i in range(size):
    dotProduct(a,b)
end = time.perf_counter()
print(f"time took to do dot product using numpy array {end-start:.4f}")

time took to do dot product using python list 0.2338
time took to do dot product using numpy array 0.2598


In [15]:
#array
import numpy as np
lst = [10,20,30]
arr=np.array(lst)
print(arr)#prints an array
print(arr.dtype)# give the datatype whether it is int or string
print(arr.shape)#gives shape
print(arr.size)# gives the length of the array
print(arr.ndim)#gives the dimensions of array


[10 20 30]
int32
(3,)
3
1


In [27]:
#array
import numpy as np
lst = ([[10,20,30],[40,50,60]])
arr=np.array(lst)
print(arr)#prints an array
print(arr.dtype)# give the datatype whether it is int or string
print(arr.shape)#gives shape
print(arr.size)# gives the length of the array
print(arr.ndim)#gives the dimensions of array

[[10 20 30]
 [40 50 60]]
int32
(2, 3)
6
2


In [7]:
# Creation of arrays
#Arange function will works as slicing 
arr = np.arange(10)
print(arr)
arr1 = np.arange(10,101,10)# takes 10 from starting and 101 works as exclusive and 10 as steps
print(arr1)
arr2 = np.arange(10,100) #(10 as start value,100 as end value)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[ 10  20  30  40  50  60  70  80  90 100]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [17]:
for i in range(0,7,1):
    print("#"*i)


#
##
###
####
#####
######


In [25]:
#converting numbers into the int,float,str,bool,complex
arr = np.array([10,20,30],dtype="str")
print(arr)
arr = np.array([10,20,30],dtype="float")
print(arr)
arr = np.array([10,20,30],dtype="bool")
print(arr)
arr = np.array([10,20,30],dtype="complex")
print(arr)
arr = np.array([10,20,30],dtype="int")
print(arr)

['10' '20' '30']
[10. 20. 30.]
[ True  True  True]
[10.+0.j 20.+0.j 30.+0.j]
[10 20 30]


In [35]:
# linspace----->np.linspace
#q  = print 10 steps between 0&1
arr = np.linspace(0,1,retstep = True)
print(arr)
arr = np.linspace(5,6,endpoint=False,retstep = True,dtype = "int")
print(arr)

(array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ]), 0.02040816326530612)
(array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5]), 0.02)


In [45]:
#zero---->zero dimension
zeroarr = np.zeros(10,"int")
print(zeroarr)
zeroarr = np.zeros((3,3,2))#1st value says how many 2d dimensions we want and 2nd value gives rows and 3rd value gives the columns
print(zeroarr)
zeroarr = np.zeros((10,3,3))#1st value says how many 2d dimensions we want and 2nd value gives rows and 3rd value gives the columns
print(zeroarr)

[0 0 0 0 0 0 0 0 0 0]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [51]:
#full---->np.full
arr = np.full(10,fill_value=5)
print(arr)
arr = np.full((2,3),fill_value=5)
print(arr)
arr = np.full((3,3),fill_value=5)
print(arr)

[5 5 5 5 5 5 5 5 5 5]
[[5 5 5]
 [5 5 5]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [17]:
#randomint ----> np.random.randint()
#randit used used to create a random number
import numpy as np
a = np.random.randint(10)# given a ending value such as it will generate b/w 1 to 10
print(a)
a = np.random.randint(10,100)
print(a)
arr1 = np.random.randint(10,100,(2,3))
print(arr1)
arr2 = np.random.randint(10,100,(2,3),"int8")
print(arr2.dtype)
print(arr2)

1
56
[[30 44 60]
 [43 25 33]]
int8
[[25 73 75]
 [56 62 38]]


In [21]:
import sys
print(f"memory consumed by arr1 is {sys.getsizeof(arr1)}")
print(f"memory consumed by arr2 is {sys.getsizeof(arr2)}")

memory consumed by arr1 is 152
memory consumed by arr2 is 134


In [23]:
arr1 = np.random.randint(10,100,(2,3))
print(arr1)
print(arr1.dtype)

[[81 68 49]
 [79 33 44]]
int32


In [25]:
# astype function 
arr1 = np.random.randint(10,100,(2,3))
print(arr1.astype("float"))

[[60. 12. 64.]
 [69. 68. 28.]]


In [39]:
#eye function
arr = np.eye(2,3,k=1)
print(arr)
arr = np.eye(5,5,k=1,dtype="int")
print(arr)

[[0. 1. 0.]
 [0. 0. 1.]]
[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]


In [41]:
#identity function will always be 0 if we pass 1 it will throw an error
arr = np.identity(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [59]:
# diagnol function--->np.diag
# 1d diag gives 2d output
#2d diag gives 1d
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([[10,20],[30,40],[50,60]])
print(arr1)
print(arr2)
rarr1 = np.diag(arr1)
print("rarr1",arr1)
rarr1 = np.diag(arr1, k=1)
print("rarr1",arr1)
rarr2 = np.diag(arr2, k=1)
print("rarr2",arr2)


[10 20 30 40 50]
[[10 20]
 [30 40]
 [50 60]]
rarr1 [10 20 30 40 50]
rarr1 [10 20 30 40 50]
rarr2 [[10 20]
 [30 40]
 [50 60]]


In [61]:
#reshape function--->np.reshape
a = np.arange(10,100,10)
print(a)
print(a.reshape(3,3))

[10 20 30 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
