In [5]:
#why pyrhon?
#* python lists are very slow in performing complex mathematical operation so we use numpy

import numpy as np
arr = np.array([10,20,30])
print(arr)
print(np.__version__)

[10 20 30]
1.26.4


In [7]:
#printing the float
arr = np.array([10.2,13.5])
print(arr)

[10.2 13.5]


In [23]:
#lists v/s Numpy
lst = [10,30,40]
c = lst+2
print(c)

TypeError: can only concatenate list (not "int") to list

In [21]:
#by using the numpy we same as we did in the list
arr = (np.array([10,20,30]))# we will add 2 numbers
print(arr+2)

[12 22 32]


In [27]:
#Importance of numpy
#*numpy is helpful in createing an dimensional array.(2D,3D,4D...ND)
#*numpy is the backbone of remaining libraries like pandas,matplotlib,scikit etc
#*it will helpful in  the visualization
# numpy has vectorization features
#NEEDS OF NUMPY:
#*creation of array, it perform operations on those array
#integral calclas
#*swfferentail equations
#*statistical related operation
#difference b'w numpy and array
#*list is python builti type but numpy we have to install
#*list can store both homogeneous and heterogenous data but numpy only store homogeneous data
#*in list we can"t perform vector operations and numpy we can perform i n-demensional array
#*arrays condsume less memory than list
#*numpy arrays are more cionvinenr to use while performing multiple complex operations.

In [35]:
import numpy as np
import sys
lst = [10,20,30,40,50,60,70,80,90,100,200,300,400]
arr = np.array([10,20,30,40,50,60,70,80,90,100,200,300,400])
print(f"the size of the list:{sys.getsizeof(lst)} bytes")
print(f"the size of the array:{sys.getsizeof(arr)} bytes")
print(f"the size of the elements in the list:{sys.getsizeof(lst)+sum(i for i in lst)} bytes")
print(f"the size of the elements in the array:{sys.getsizeof(arr)+sum(i for i in arr)} bytes")

the size of the list:168 bytes
the size of the array:164 bytes
the size of the elements in the list:1618 bytes
the size of the elements in the array:1614 bytes


In [41]:
import time
size = 1000
a = list(range(size))
b = list(range(size))
def dotProduct(a,b):
    ans = 0
    for i,j in zip(a,b):
        ans+= i*j
    return ans
start = time.perf_counter()
for i in range(size):
    dotProduct(a,b)
end = time.perf_counter()
x = np.array(range(size))
y = np.array(range(size))
print(f"time took to do dot product using python list {end-start:.4f}")
start = time.perf_counter()
for i in range(size):
    dotProduct(a,b)
end = time.perf_counter()
print(f"time took to do dot product using numpy array {end-start:.4f}")

time took to do dot product using python list 0.2338
time took to do dot product using numpy array 0.2598


In [15]:
#array
import numpy as np
lst = [10,20,30]
arr=np.array(lst)
print(arr)#prints an array
print(arr.dtype)# give the datatype whether it is int or string
print(arr.shape)#gives shape
print(arr.size)# gives the length of the array
print(arr.ndim)#gives the dimensions of array


[10 20 30]
int32
(3,)
3
1


In [27]:
#array
import numpy as np
lst = ([[10,20,30],[40,50,60]])
arr=np.array(lst)
print(arr)#prints an array
print(arr.dtype)# give the datatype whether it is int or string
print(arr.shape)#gives shape
print(arr.size)# gives the length of the array
print(arr.ndim)#gives the dimensions of array

[[10 20 30]
 [40 50 60]]
int32
(2, 3)
6
2


In [7]:
# Creation of arrays
#Arange function will works as slicing 
arr = np.arange(10)
print(arr)
arr1 = np.arange(10,101,10)# takes 10 from starting and 101 works as exclusive and 10 as steps
print(arr1)
arr2 = np.arange(10,100) #(10 as start value,100 as end value)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[ 10  20  30  40  50  60  70  80  90 100]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [17]:
for i in range(0,7,1):
    print("#"*i)


#
##
###
####
#####
######


In [25]:
#converting numbers into the int,float,str,bool,complex
arr = np.array([10,20,30],dtype="str")
print(arr)
arr = np.array([10,20,30],dtype="float")
print(arr)
arr = np.array([10,20,30],dtype="bool")
print(arr)
arr = np.array([10,20,30],dtype="complex")
print(arr)
arr = np.array([10,20,30],dtype="int")
print(arr)

['10' '20' '30']
[10. 20. 30.]
[ True  True  True]
[10.+0.j 20.+0.j 30.+0.j]
[10 20 30]


In [35]:
# linspace----->np.linspace
#q  = print 10 steps between 0&1
arr = np.linspace(0,1,retstep = True)
print(arr)
arr = np.linspace(5,6,endpoint=False,retstep = True,dtype = "int")
print(arr)

(array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ]), 0.02040816326530612)
(array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5]), 0.02)


In [45]:
#zero---->zero dimension
zeroarr = np.zeros(10,"int")
print(zeroarr)
zeroarr = np.zeros((3,3,2))#1st value says how many 2d dimensions we want and 2nd value gives rows and 3rd value gives the columns
print(zeroarr)
zeroarr = np.zeros((10,3,3))#1st value says how many 2d dimensions we want and 2nd value gives rows and 3rd value gives the columns
print(zeroarr)

[0 0 0 0 0 0 0 0 0 0]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [51]:
#full---->np.full
arr = np.full(10,fill_value=5)
print(arr)
arr = np.full((2,3),fill_value=5)
print(arr)
arr = np.full((3,3),fill_value=5)
print(arr)

[5 5 5 5 5 5 5 5 5 5]
[[5 5 5]
 [5 5 5]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [17]:
#randomint ----> np.random.randint()
#randit used used to create a random number
import numpy as np
a = np.random.randint(10)# given a ending value such as it will generate b/w 1 to 10
print(a)
a = np.random.randint(10,100)
print(a)
arr1 = np.random.randint(10,100,(2,3))
print(arr1)
arr2 = np.random.randint(10,100,(2,3),"int8")
print(arr2.dtype)
print(arr2)

1
56
[[30 44 60]
 [43 25 33]]
int8
[[25 73 75]
 [56 62 38]]


In [21]:
import sys
print(f"memory consumed by arr1 is {sys.getsizeof(arr1)}")
print(f"memory consumed by arr2 is {sys.getsizeof(arr2)}")

memory consumed by arr1 is 152
memory consumed by arr2 is 134


In [23]:
arr1 = np.random.randint(10,100,(2,3))
print(arr1)
print(arr1.dtype)

[[81 68 49]
 [79 33 44]]
int32


In [25]:
# astype function 
arr1 = np.random.randint(10,100,(2,3))
print(arr1.astype("float"))

[[60. 12. 64.]
 [69. 68. 28.]]


In [39]:
#eye function
arr = np.eye(2,3,k=1)
print(arr)
arr = np.eye(5,5,k=1,dtype="int")
print(arr)

[[0. 1. 0.]
 [0. 0. 1.]]
[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]


In [41]:
#identity function will always be 0 if we pass 1 it will throw an error
arr = np.identity(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [59]:
# diagnol function--->np.diag
# 1d diag gives 2d output
#2d diag gives 1d
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([[10,20],[30,40],[50,60]])
print(arr1)
print(arr2)
rarr1 = np.diag(arr1)
print("rarr1",arr1)
rarr1 = np.diag(arr1, k=1)
print("rarr1",arr1)
rarr2 = np.diag(arr2, k=1)
print("rarr2",arr2)


[10 20 30 40 50]
[[10 20]
 [30 40]
 [50 60]]
rarr1 [10 20 30 40 50]
rarr1 [10 20 30 40 50]
rarr2 [[10 20]
 [30 40]
 [50 60]]


In [61]:
#reshape function--->np.reshape
a = np.arange(10,100,10)
print(a)
print(a.reshape(3,3))

[10 20 30 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [9]:
#rand fun---> np.rand used for generating float numbers.
import numpy as np
a = np.random.rand(10)# given a ending value such as it will generate b/w 1 to 10
print(a)
print(np.random.rand(10))
a=np.random.rand(2,3)#2 rows 3 colomns
print(a)
a = np.random.rand(3,2,3)#3 dim,2 rows,3 columns
print(a)

[0.53687617 0.23197115 0.88722522 0.62506409 0.02344337 0.94777888
 0.67720398 0.1985307  0.64087329 0.65301312]
[0.6630488  0.79324043 0.14504803 0.84490668 0.07712181 0.01826964
 0.14621045 0.57952991 0.69720469 0.25595928]
[[0.94263496 0.35906909 0.79083044]
 [0.42098889 0.35240313 0.11746976]]
[[[0.95266008 0.0384057  0.57350166]
  [0.80362603 0.69204036 0.11074066]]

 [[0.37008848 0.52199095 0.33698628]
  [0.09419876 0.22346063 0.29493604]]

 [[0.2343569  0.22660447 0.58889913]
  [0.79276429 0.70741595 0.59864992]]]


In [17]:
#randn fun----> used in the normal distribution
print(np.random.randn())
print(np.random.randn(10))
print(np.random.randn(2,3))
print(np.random.randn(3,2,3))

1.2241274809990357
[-1.10510468 -0.13585132  0.04431561  0.74994318  0.48527886 -0.86583154
 -1.11492388 -1.85561618  1.5121853  -0.78286831]
[[ 0.8019357  -0.0192226  -0.00945874]
 [ 0.85172307  0.20790231 -0.11413381]]
[[[ 0.47234973 -0.32157161 -1.57884221]
  [-1.50346171 -3.2032857  -0.84797526]]

 [[ 0.58651153  0.28814913 -0.26116933]
  [ 1.11367296  0.29426011  0.71943446]]

 [[-0.07691216  1.17680128  1.01163882]
  [ 0.16953825  1.37035298 -0.63969368]]]


In [45]:
#np.random.uniform fun---> gives a equal values
print(np.random.uniform(10))
print(np.random.uniform(2,3, size=(2,3)))#gives values between 2&3

9.527688271189039
[[2.73817949 2.82986138 2.4309482 ]
 [2.0488745  2.31252845 2.46148158]]


In [ ]:
#numpy data tyoes
# integer---> (int8,int16,int32,int64) -i
# float---->(float32,float64) - float
# string---->-s
#bolen -b
#unicode string --->u
#datetime--->M
#unsigned integer---> -u-(uint8,uint16,uint32,64)


In [68]:
#Shuffle function--->np.random.shuffle
arr = np.arange(1,19).reshape(3,2,3)
print(f"array before shuffling:\n {arr}")
np.random.shuffle(arr)
print(f"array after shuffling:\n {arr}")

#VIEW FUN--->np.view (used for the shallow function)
arr = np.arange(1,11)
varr = arr.view()
print(f"original array:\n{arr}")
print(f"copied array:\n{varr}")
varr[0] =99
print(varr)

#copy FUN--->np.copy (used for the deep copy function)
arr = np.arange(1,11)
varr = arr.copy()
print(f"original array:\n{arr}")
print(f"copied array:\n{varr}")
varr[0] =99
print(varr)

array before shuffling:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
array after shuffling:
 [[[13 14 15]
  [16 17 18]]

 [[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
original array:
[ 1  2  3  4  5  6  7  8  9 10]
copied array:
[ 1  2  3  4  5  6  7  8  9 10]
[99  2  3  4  5  6  7  8  9 10]
original array:
[ 1  2  3  4  5  6  7  8  9 10]
copied array:
[ 1  2  3  4  5  6  7  8  9 10]
[99  2  3  4  5  6  7  8  9 10]


In [70]:
# Data types
arr = np.arange(1,11)
varr = np.float32(arr)
print(f"original array:\n{arr}")
print(f"changed array:\n{varr}")

original array:
[ 1  2  3  4  5  6  7  8  9 10]
changed array:
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [72]:
# Data types
arr = np.arange(1,11)
varr = np.bool_(arr)
print(f"original array:\n{arr}")
print(f"changed array:\n{varr}")

original array:
[ 1  2  3  4  5  6  7  8  9 10]
changed array:
[ True  True  True  True  True  True  True  True  True  True]


In [33]:
#Accessing the elements of np.array through indexing
import numpy as np
arr = np.arange(1,11)
print(arr)
print(arr[5])
arr = np.arange(1,10).reshape(3,3)
print(arr)
print(arr[2][2])
arr = np.arange(1,25).reshape(2,3,4)
print(arr)
print(arr[0][2][2])

[ 1  2  3  4  5  6  7  8  9 10]
6
[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
11


In [39]:
#Accessing the elements of np.array through SLICEING
arr = np.arange(1,11)
print(arr)
print(arr[2:8])# doing slicing in the array
arr = np.arange(1,10).reshape(3,3)
print(arr)
print(arr[0:2,2:])#takes(rowindex,column index)(in row index it takes(start:stop:steps)(here[0 is starting:2 is exclusive it only considers 0&1] same for column index)
arr = np.arange(1,19).reshape(2,3,3)
print(arr)
print(arr[0:1,0:2,1:])

[ 1  2  3  4  5  6  7  8  9 10]
[3 4 5 6 7 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3]
 [6]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
[[[2 3]
  [5 6]]]


In [61]:
#Accessing the elements of np.array through ADVANCE INDEXING
arr = np.arange(1,11)
print(arr)
arr1 = np.array([0,3,7,9])
print(arr[arr1])
arr = np.arange(1,10).reshape(3,3)#2d array
print(arr)
print("access the elements in the 2d array:", arr[[0,1,2],[2,1,0]])# it takes ([row indexses we want],[column indexes we want])
arr = np.arange(1,19).reshape(2,3,3)#3d array
print(arr)
print("accessing the elements in the 3d array:",arr[[0,1,1,1],[0,1,0,1],[1,0,1,2]])

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  4  8 10]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
access the elements in the 2d array: [3 5 7]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
accessing the elements in the 3d array: [ 2 13 11 15]


In [25]:
# iterating the elements of array using for loop
import numpy as np
a=np.arange(1,11) # 1d array
print(a)
for i in a:
    print(f"the 1d array elements are:\n{i}")
arr = np.arange(1,10).reshape(3,3)# 2d array
print(arr)
for i in arr:
    for j in i:
        print(f"the 2d array elements are:\n{j}")

arr = np.arange(1,19).reshape(2,3,3)# 2d array
print(arr)
for i in arr:
    for j in i:
        for k in j:
            print(f"the 3d array elements are:\n{k}")
        

[ 1  2  3  4  5  6  7  8  9 10]
the 1d array elements are:
1
the 1d array elements are:
2
the 1d array elements are:
3
the 1d array elements are:
4
the 1d array elements are:
5
the 1d array elements are:
6
the 1d array elements are:
7
the 1d array elements are:
8
the 1d array elements are:
9
the 1d array elements are:
10
[[1 2 3]
 [4 5 6]
 [7 8 9]]
the 2d array elements are:
1
the 2d array elements are:
2
the 2d array elements are:
3
the 2d array elements are:
4
the 2d array elements are:
5
the 2d array elements are:
6
the 2d array elements are:
7
the 2d array elements are:
8
the 2d array elements are:
9
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
the 3d array elements are:
1
the 3d array elements are:
2
the 3d array elements are:
3
the 3d array elements are:
4
the 3d array elements are:
5
the 3d array elements are:
6
the 3d array elements are:
7
the 3d array elements are:
8
the 3d array elements are:
9
the 3d array elements are:
10
the 3d array el

In [33]:
#nditer fun---->used to iterate the elements
arr = np.arange(1,11)
print(arr)
for i in np.nditer(arr):
    print(f"the 1d array eleents are :\n{i}")

arr = np.arange(1,10).reshape(3,3)
print(arr)
for i in np.nditer(arr):
    print(f"the 2d array eleents are :\n{i}")

arr = np.arange(1,19).reshape(2,3,3)
print(arr)
for i in np.nditer(arr):
    print(f"the 3d array eleents are :\n{i}")

[ 1  2  3  4  5  6  7  8  9 10]
the 1d array eleents are :
1
the 1d array eleents are :
2
the 1d array eleents are :
3
the 1d array eleents are :
4
the 1d array eleents are :
5
the 1d array eleents are :
6
the 1d array eleents are :
7
the 1d array eleents are :
8
the 1d array eleents are :
9
the 1d array eleents are :
10
[[1 2 3]
 [4 5 6]
 [7 8 9]]
the 2d array eleents are :
1
the 2d array eleents are :
2
the 2d array eleents are :
3
the 2d array eleents are :
4
the 2d array eleents are :
5
the 2d array eleents are :
6
the 2d array eleents are :
7
the 2d array eleents are :
8
the 2d array eleents are :
9
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
the 3d array eleents are :
1
the 3d array eleents are :
2
the 3d array eleents are :
3
the 3d array eleents are :
4
the 3d array eleents are :
5
the 3d array eleents are :
6
the 3d array eleents are :
7
the 3d array eleents are :
8
the 3d array eleents are :
9
the 3d array eleents are :
10
the 3d array el

In [43]:
#accessing the elements with there index using ndenumerate
arr= np.arange(1,11)# 1D array
print(arr)
for i in np.ndenumerate(arr):
    print(f"the index of the elements{i}")

arr= np.arange(1,10).reshape(3,3)
print(arr)
for i,j in np.ndenumerate(arr):
    print(f"the elements of {j} positioned {i}")

arr= np.arange(1,19).reshape(2,3,3)
print(arr)
for i,j in np.ndenumerate(arr):
    print(f"the elements of {j} positioned {i}")

[ 1  2  3  4  5  6  7  8  9 10]
the index of the elements((0,), 1)
the index of the elements((1,), 2)
the index of the elements((2,), 3)
the index of the elements((3,), 4)
the index of the elements((4,), 5)
the index of the elements((5,), 6)
the index of the elements((6,), 7)
the index of the elements((7,), 8)
the index of the elements((8,), 9)
the index of the elements((9,), 10)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
the elements of 1 positioned (0, 0)
the elements of 2 positioned (0, 1)
the elements of 3 positioned (0, 2)
the elements of 4 positioned (1, 0)
the elements of 5 positioned (1, 1)
the elements of 6 positioned (1, 2)
the elements of 7 positioned (2, 0)
the elements of 8 positioned (2, 1)
the elements of 9 positioned (2, 2)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
the elements of 1 positioned (0, 0, 0)
the elements of 2 positioned (0, 0, 1)
the elements of 3 positioned (0, 0, 2)
the elements of 4 positioned (0, 1, 0)
the elements of 5 positione

In [67]:
# Arthmatic operations: it won't operate on 2 elemnts  but it multiply on array by the given numbers by us
arr = np.arange(1,11)
print(arr)
print(f"subtraction of array arr-2 :\n{arr-2}")
print(f"addition of array arr+2 :\n{arr+2}")
print(f"multiplication of array arr*2 :\n{arr*2}")
print(f"division of array arr/2 :\n{arr/2}")
print(f"modulus of array arr%2 :\n{arr%2}")
print(f"floor devision of array arr//2 :\n{arr//2}")
print(f"exponent of array arr^2:\n{arr^2}")
print(f"power of array arr**2 :\n{arr**2}")

[ 1  2  3  4  5  6  7  8  9 10]
subtraction of array arr-2 :
[-1  0  1  2  3  4  5  6  7  8]
addition of array arr+2 :
[ 3  4  5  6  7  8  9 10 11 12]
multiplication of array arr*2 :
[ 2  4  6  8 10 12 14 16 18 20]
division of array arr/2 :
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
modulus of array arr%2 :
[1 0 1 0 1 0 1 0 1 0]
floor devision of array arr//2 :
[0 1 1 2 2 3 3 4 4 5]
exponent of array arr^2:
[ 3  0  1  6  7  4  5 10 11  8]
power of array arr**2 :
[  1   4   9  16  25  36  49  64  81 100]


In [63]:
# Arthmatic operations: it won't operate on 2 elemnts  but it multiply on array by the given numbers by us
arr = np.arange(1,10).reshape(3,3)
print(arr)
print(f"subtraction of array arr-2 :\n{arr-2}")
print(f"addition of array arr+2 :\n{arr+2}")
print(f"multiplication of array arr*2 :\n{arr*2}")
print(f"division of array arr/2 :\n{arr/2}")
print(f"modulus of array arr%2 :\n{arr%2}")
print(f"floor devision of array arr//2 :\n{arr//2}")
print(f"exponent of array arr^2:\n{arr^2}")
print(f"power of array arr**2 :\n{arr**2}")



[[1 2 3]
 [4 5 6]
 [7 8 9]]
subtraction of array arr-2 :
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
addition of array arr+2 :
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
multiplication of array arr*2 :
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
division of array arr/2 :
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
modulus of array arr%2 :
[[1 0 1]
 [0 1 0]
 [1 0 1]]
floor devision of array arr//2 :
[[0 1 1]
 [2 2 3]
 [3 4 4]]
exponent of array arr^2:
[[ 3  0  1]
 [ 6  7  4]
 [ 5 10 11]]
power of array arr**2 :
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [65]:
arr = np.arange(1,19).reshape(2,3,3)
print(arr)
print(f"subtraction of array arr-2 :\n{arr-2}")
print(f"addition of array arr+2 :\n{arr+2}")
print(f"multiplication of array arr*2 :\n{arr*2}")
print(f"division of array arr/2 :\n{arr/2}")
print(f"modulus of array arr%2 :\n{arr%2}")
print(f"floor devision of array arr//2 :\n{arr//2}")
print(f"exponent of array arr^2:\n{arr^2}")
print(f"power of array arr**2 :\n{arr**2}")

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
subtraction of array arr-2 :
[[[-1  0  1]
  [ 2  3  4]
  [ 5  6  7]]

 [[ 8  9 10]
  [11 12 13]
  [14 15 16]]]
addition of array arr+2 :
[[[ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]]]
multiplication of array arr*2 :
[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[20 22 24]
  [26 28 30]
  [32 34 36]]]
division of array arr/2 :
[[[0.5 1.  1.5]
  [2.  2.5 3. ]
  [3.5 4.  4.5]]

 [[5.  5.5 6. ]
  [6.5 7.  7.5]
  [8.  8.5 9. ]]]
modulus of array arr%2 :
[[[1 0 1]
  [0 1 0]
  [1 0 1]]

 [[0 1 0]
  [1 0 1]
  [0 1 0]]]
floor devision of array arr//2 :
[[[0 1 1]
  [2 2 3]
  [3 4 4]]

 [[5 5 6]
  [6 7 7]
  [8 8 9]]]
exponent of array arr^2:
[[[ 3  0  1]
  [ 6  7  4]
  [ 5 10 11]]

 [[ 8  9 14]
  [15 12 13]
  [18 19 16]]]
power of array arr**2 :
[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[100 121 144]
  [169 196 225]
  [256 289 324]]]


In [75]:
# arthmatic operation between 2 arrays:
# *should be same dimension(ndim),size(size),shape(shape)
arr1 = np.arange(1,6)
arr2 = np.arange(10,60,10)
print(arr1)
print(arr2)
print(f"the dimension of the arr1 is {arr1.ndim}, the shape of arr1 is {arr1.shape}, The size of the arr1 is {arr1.size}")
print(f"the dimension of the arr2 is {arr2.ndim}, the shape of arr2 is {arr2.shape}, The size of the arr2 is {arr2.size}")
print(f"subtraction of array arr1-arr2 :\n{arr1-arr2}")
print(f"addition of array arr1+arr2 :\n{arr1+arr2}")
print(f"multiplication of array arr1*arr2 :\n{arr1*arr2}")
print(f"division of array arr1/arr2 :\n{arr1/arr2}")
print(f"modulus of array arr1%arr2 :\n{arr1%arr2}")
print(f"floor devision of array arr1//arr2 :\n{arr1//arr2}")
print(f"exponent of array arr1^arr2:\n{arr1^arr2}")
print(f"power of array arr1**arr2 :\n{arr1**arr2}")

[1 2 3 4 5]
[10 20 30 40 50]
the dimension of the arr1 is 1, the shape of arr1 is (5,), The size of the arr1 is 5
the dimension of the arr2 is 1, the shape of arr2 is (5,), The size of the arr2 is 5
subtraction of array arr1-arr2 :
[ -9 -18 -27 -36 -45]
addition of array arr1+arr2 :
[11 22 33 44 55]
multiplication of array arr1*arr2 :
[ 10  40  90 160 250]
division of array arr1/arr2 :
[0.1 0.1 0.1 0.1 0.1]
modulus of array arr1%arr2 :
[1 2 3 4 5]
floor devision of array arr1//arr2 :
[0 0 0 0 0]
exponent of array arr1^arr2:
[11 22 29 44 55]
power of array arr1**arr2 :
[          1     1048576 -1010140999           0  1296002393]


In [3]:
#BOARDCASTING
import numpy as np
arr1 = np.arange(1,3)
arr2 = np.arange(10,81,10).reshape(2,2,2)
print(arr1)
print(arr2)
print(f"the dimension of the arr1 is {arr1.ndim}, the shape of arr1 is {arr1.shape}, The size of the arr1 is {arr1.size}")
print(f"the dimension of the arr2 is {arr2.ndim}, the shape of arr2 is {arr2.shape}, The size of the arr2 is {arr2.size}")
print(f"subtraction of array arr1-arr2 :\n{arr1-arr2}")
print(f"addition of array arr1+arr2 :\n{arr1+arr2}")
print(f"multiplication of array arr1*arr2 :\n{arr1*arr2}")
print(f"division of array arr1/arr2 :\n{arr1/arr2}")
print(f"modulus of array arr1%arr2 :\n{arr1%arr2}")
print(f"floor devision of array arr1//arr2 :\n{arr1//arr2}")
print(f"exponent of array arr1^arr2:\n{arr1^arr2}")
print(f"power of array arr1**arr2 :\n{arr1**arr2}")

[1 2]
[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]
the dimension of the arr1 is 1, the shape of arr1 is (2,), The size of the arr1 is 2
the dimension of the arr2 is 3, the shape of arr2 is (2, 2, 2), The size of the arr2 is 8
subtraction of array arr1-arr2 :
[[[ -9 -18]
  [-29 -38]]

 [[-49 -58]
  [-69 -78]]]
addition of array arr1+arr2 :
[[[11 22]
  [31 42]]

 [[51 62]
  [71 82]]]
multiplication of array arr1*arr2 :
[[[ 10  40]
  [ 30  80]]

 [[ 50 120]
  [ 70 160]]]
division of array arr1/arr2 :
[[[0.1        0.1       ]
  [0.03333333 0.05      ]]

 [[0.02       0.03333333]
  [0.01428571 0.025     ]]]
modulus of array arr1%arr2 :
[[[1 2]
  [1 2]]

 [[1 2]
  [1 2]]]
floor devision of array arr1//arr2 :
[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
exponent of array arr1^arr2:
[[[11 22]
  [31 42]]

 [[51 62]
  [71 82]]]
power of array arr1**arr2 :
[[[      1 1048576]
  [      1       0]]

 [[      1       0]
  [      1       0]]]


In [16]:
# RESize
arr=np.arange(6)
varr=arr.resize(arr,())
print(varr)
print(arr)

TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
#reshape
arr=np.arange(1,10)
varr=arr.reshape(3,-4,order ='F')
varr=arr.reshape(3,-4,order ='C')
print(varr)
print(arr)

In [20]:
#FLATTEN
arr =np.arange(10,91,10).reshape(3,3)
print(arr)
print(arr.flatten('F'))


[[10 20 30]
 [40 50 60]
 [70 80 90]]
[10 40 70 20 50 80 30 60 90]


In [22]:
#FLAT VARIABLE
arr =np.arange(10,91,10).reshape(3,3)
print(arr)
for i in arr.flat:
    print(i)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
10
20
30
40
50
60
70
80
90


In [24]:
#FLATTEN
arr =np.arange(10,91,10).reshape(3,3)
print(arr)
print(arr.flatten('F'))
varr = arr[0][1]=99
print(varr)


[[10 20 30]
 [40 50 60]
 [70 80 90]]
[10 40 70 20 50 80 30 60 90]
99


In [15]:
#TRANSPOSE FUNCTION
import numpy as np
arr = np.arange(1,6)
print(f"the normal array:\n{arr}")
tarr = np.transpose(arr)
print(f"the transposed array is:\n{tarr}")
#2d array
arr = np.arange(1,10).reshape(3,3)
print(f"the normal array:\n{arr}")
tarr = np.transpose(arr)
print(f"the transposed array is:\n{tarr}")
#3d array
arr = np.arange(1,19).reshape(2,3,3)
print(f"the normal array:\n{arr}")
tarr = np.transpose(arr,axes=(1,2,0))
print(f"the transposed array is:\n{tarr}")

the normal array:
[1 2 3 4 5]
the transposed array is:
[1 2 3 4 5]
the normal array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
the transposed array is:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
the normal array:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
the transposed array is:
[[[ 1 10]
  [ 2 11]
  [ 3 12]]

 [[ 4 13]
  [ 5 14]
  [ 6 15]]

 [[ 7 16]
  [ 8 17]
  [ 9 18]]]


In [29]:
#* pattern printing
n = int(input("enter a number"))
for i in range(1,n+1):
    print("*"*i)
    


enter a number 8


*
**
***
****
*****
******
*******
********


In [41]:
#Swapaxes
arr = np.arange(1,61). reshape(3,4,5)
print(arr)
tarr = np.swapaxes(arr,2,0)#0 means 3 rows
print(f"the swapaxes array is :\n{tarr}")
print("hello",tarr)


[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]
the swapaxes array is :
[[[ 1 21 41]
  [ 6 26 46]
  [11 31 51]
  [16 36 56]]

 [[ 2 22 42]
  [ 7 27 47]
  [12 32 52]
  [17 37 57]]

 [[ 3 23 43]
  [ 8 28 48]
  [13 33 53]
  [18 38 58]]

 [[ 4 24 44]
  [ 9 29 49]
  [14 34 54]
  [19 39 59]]

 [[ 5 25 45]
  [10 30 50]
  [15 35 55]
  [20 40 60]]]
hello [[[ 1 21 41]
  [ 6 26 46]
  [11 31 51]
  [16 36 56]]

 [[ 2 22 42]
  [ 7 27 47]
  [12 32 52]
  [17 37 57]]

 [[ 3 23 43]
  [ 8 28 48]
  [13 33 53]
  [18 38 58]]

 [[ 4 24 44]
  [ 9 29 49]
  [14 34 54]
  [19 39 59]]

 [[ 5 25 45]
  [10 30 50]
  [15 35 55]
  [20 40 60]]]


In [49]:
#Joining of n arrays into 1 array
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6,7,8,9])
arr3 = np.array([100,200])
res = np.empty(11)
con = np.concatenate((arr1,arr2,arr3), out = res)
print(con)

[  1.   2.   3.   4.   5.   6.   7.   8.   9. 100. 200.]


In [24]:
import numpy as np
arr = np.arange(1,6)
print(arr)
arr1 = arr**3
arr2 = np.resize(arr1, (2,3))
print(arr2)

[1 2 3 4 5]
[[  1   8  27]
 [ 64 125   1]]


In [83]:
#joining of 2 arrays
arr1 = np.array(["a","b","c","d","e","f"])
arr2 = np.array(["g","h","i","j","k","l"])
arr3 = np.reshape(arr1,(2,3))
arr4 = np.reshape(arr2,(2,3))
print(arr3)
print(arr4)
arr5 = np.concatenate((arr3,arr4))
arr6 = np.reshape(arr5,(4,3))
print(arr6)



[['a' 'b' 'c']
 ['d' 'e' 'f']]
[['g' 'h' 'i']
 ['j' 'k' 'l']]
[['a' 'b' 'c']
 ['d' 'e' 'f']
 ['g' 'h' 'i']
 ['j' 'k' 'l']]


In [71]:
a = np.arange(1,25).reshape(2,3,4)
print(a)
tarr = np.transpose(a)
print(f"the transpose array is :\n{tarr}")

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
the transpose array is :
[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]


In [103]:
#stack
arr1 = np.array(["a","b","c","d","e","f"])
arr2 = np.array (["g","h","i","j","k","l"])
arr3 = np.reshape(arr1,(2,3))
arr4 = np.reshape(arr2,(2,3))
print(arr3)
print(arr4)
arr5 =(np.stack((arr3,arr4)))
print(arr5)


[['a' 'b' 'c']
 ['d' 'e' 'f']]
[['g' 'h' 'i']
 ['j' 'k' 'l']]
[[['a' 'b' 'c']
  ['d' 'e' 'f']]

 [['g' 'h' 'i']
  ['j' 'k' 'l']]]


In [99]:
# stack
arr1 = np.array([[10,20,30],[40,20,60]])
arr2 = np.array([[70,80,90],[20,40,50]])
sarr = (np.stack((arr1,arr2)))
print(sarr)

[[[10 20 30]
  [40 20 60]]

 [[70 80 90]
  [20 40 50]]]


In [116]:
#vstack(0) 1d+1d = 2d
arr1 = np.array([[10,20,30],[40,20,60]])
arr2 = np.array([[70,80,90],[20,40,50]])
sarr = (np.vstack((arr1,arr2)))
print(sarr)

#hstack(1) 1d+1d = 1d
arr1 = np.array([[10,20,30],[40,20,60]])
arr2 = np.array([[70,80,90],[20,40,50]])
sarr = (np.hstack((arr1,arr2)))
print(sarr)


[[10 20 30]
 [40 20 60]
 [70 80 90]
 [20 40 50]]
[[10 20 30 70 80 90]
 [40 20 60 20 40 50]]


In [124]:
#dstack(2) 1d+1d = 3d,2d+2d = 3d
arr1 = np.array([[10,20,30]])
arr2 = np.array([[70,80,90]])
sarr = (np.dstack((arr1,arr2)))
print(sarr)

arr1 = np.array([[10,20,30],[40,20,60]])
arr2 = np.array([[70,80,90],[20,40,50]])
sarr = (np.dstack((arr1,arr2)))
print(sarr)


[[[10 70]
  [20 80]
  [30 90]]]
[[[10 70]
  [20 80]
  [30 90]]

 [[40 20]
  [20 40]
  [60 50]]]


In [144]:
#boolean values
arr = np.array([0,1])
arr1 =np.resize(arr,(2,2))
arr2 = arr1.astype(bool)
print(arr1)
print(arr2)


[[0 1]
 [0 1]]
[[False  True]
 [False  True]]


In [32]:
# converting it to string
import numpy as np
a = np.arange(1,7).reshape(2,3)
print(a)
b = np.array(['one','two','three'])
print(b)
print(a.astype("str"))
c = np.concatenate((a,b), axis=None).reshape(3,3)
print(c)


[[1 2 3]
 [4 5 6]]
['one' 'two' 'three']
[['1' '2' '3']
 ['4' '5' '6']]
[['1' '2' '3']
 ['4' '5' '6']
 ['one' 'two' 'three']]


In [61]:
a = np.array([[1,2,3],['one','two','three']])
arr = np.dstack((a))
print(arr)
print(arr.flatten('F'))


[[['1' 'one']
  ['2' 'two']
  ['3' 'three']]]
['1' '2' '3' 'one' 'two' 'three']


In [82]:
#Split function
a = np.arange(1,7)
print(f"the original array are:\n{a}")
b = np.split(a,3)
print(f"the split array are:\n{b}")

#2d
a = np.arange(1,25).reshape(6,4)
print(f"the original array are:\n{a}")
b = np.split(a,2, axis = 1)
print(f"the split array are:\n{b}")

#3d
a = np.arange(1,19).reshape(2,3,3)
print(f"the original array are:\n{a}")
b = np.split(a,2)
print(f"the split array are:\n{b}")


the original array are:
[1 2 3 4 5 6]
the split array are:
[array([1, 2]), array([3, 4]), array([5, 6])]
the original array are:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
the split array are:
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16],
       [19, 20],
       [23, 24]])]
the original array are:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
the split array are:
[array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]]), array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])]


In [95]:
#spliting using the vsplit
a = np.arange(1,25).reshape(6,4)
print(f"the original array are:\n{a}")
b = np.vsplit(a,[1,2])# this fun dedicated to the vertical shape
print(f"the split array are:\n{b}")

the original array are:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
the split array are:
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])]


In [103]:
#hsplit
a = np.arange(1,7)
print(f"the original array are:\n{a}")
b = np.hsplit(a,[1,2])
print(f"the split array are:\n{b}")

#2d
a = np.arange(1,25).reshape(6,4)
print(f"the original array are:\n{a}")
b = np.hsplit(a,[1,2])
print(f"the split array are:\n{b}")

#3d
a = np.arange(1,19).reshape(2,3,3)
print(f"the original array are:\n{a}")
b = np.hsplit(a,[1,2])
print(f"the split array are:\n{b}")

the original array are:
[1 2 3 4 5 6]
the split array are:
[array([1]), array([2]), array([3, 4, 5, 6])]
the original array are:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
the split array are:
[array([[ 1],
       [ 5],
       [ 9],
       [13],
       [17],
       [21]]), array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16],
       [19, 20],
       [23, 24]])]
the original array are:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
the split array are:
[array([[[ 1,  2,  3]],

       [[10, 11, 12]]]), array([[[ 4,  5,  6]],

       [[13, 14, 15]]]), array([[[ 7,  8,  9]],

       [[16, 17, 18]]])]


In [107]:
# splitig using the dstack
a = np.arange(1,25).reshape(2,3,4)
print(f"the original array are:\n{a}")
b = np.dsplit(a,[1,2])
print(f"the split array are:\n{b}")

the original array are:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
the split array are:
[array([[[ 1],
        [ 5],
        [ 9]],

       [[13],
        [17],
        [21]]]), array([[[ 2],
        [ 6],
        [10]],

       [[14],
        [18],
        [22]]]), array([[[ 3,  4],
        [ 7,  8],
        [11, 12]],

       [[15, 16],
        [19, 20],
        [23, 24]]])]


In [109]:
#array_split is used to split the elemnts into the required sections without any thinking any required sectipns
a = np.arange(1,10)
print(f"the original array are:\n{a}")
b = np.array_split(a,[1,2])
print(f"the split array are:\n{b}")

the original array are:
[1 2 3 4 5 6 7 8 9]
the split array are:
[array([1]), array([2]), array([3, 4, 5, 6, 7, 8, 9])]


In [121]:
a = np.arange(1,21).reshape(4,5)
print(a)
#output1
b = np.hsplit(a,[1,3])
print(f"the columns values:\n{b}")
#output2
c = np.vsplit(a,[1,3])
print(f"the row values:\n{c}")
#output3
c = np.array_split(a,[1,3])
print(f"the array_split values:\n{c}")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
the columns values:
[array([[ 1],
       [ 6],
       [11],
       [16]]), array([[ 2,  3],
       [ 7,  8],
       [12, 13],
       [17, 18]]), array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20]])]
the row values:
[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]]), array([[16, 17, 18, 19, 20]])]
the array_split values:
[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]]), array([[16, 17, 18, 19, 20]])]


In [145]:
a = np.arange(1,11)
print(a)
lst=[1,4,7]
sarr = a[lst]
varr = sarr+10
print(np.resize(varr,(3,3)))



[ 1  2  3  4  5  6  7  8  9 10]
[[12 15 18]
 [12 15 18]
 [12 15 18]]


In [40]:
#SORTING OF AN ARRAY
#* Sorting will happen in ascending order if there are numbers
#* sif there are strings then it will happen based on the alphabets
#*uses quick sort and the ascending order

import numpy as np
a = np.array([80,70,90,60,40,50,30,10,20])
b=np.sort(a)
print(f"the sorted array is:\n{b}")
c = np.sort(-a)
print(f"the sorted array in the negative values is:\n{c}")
d = np.sort(a, axis=0)
print(f"the sorted array with the axis is:\n{d}")
arr = np.array(["Rashmika","anushka","katrina","vijay","zoy"])
np.sort(arr)
# sorting 2d array using axis
arr = np.array([[40,30,20],[70,60,80],[100,90,10]])
d = np.sort(arr, axis=0)#uding axis 0
print(f"the sorted array with the axis 0 is:\n{d}")
arr = np.array([[40,30,20],[70,60,80],[100,90,10]])
d = np.sort(arr, axis=1)#uding axis 1
print(f"the sorted array with the axis 1 is:\n{d}")

the sorted array is:
[10 20 30 40 50 60 70 80 90]
the sorted array in the negative values is:
[-90 -80 -70 -60 -50 -40 -30 -20 -10]
the sorted array with the axis is:
[10 20 30 40 50 60 70 80 90]
the sorted array with the axis 0 is:
[[ 40  30  10]
 [ 70  60  20]
 [100  90  80]]
the sorted array with the axis 1 is:
[[ 20  30  40]
 [ 60  70  80]
 [ 10  90 100]]


In [48]:
names = [("names","S10"),("age",int),("marks",float)]
values = [("ram",21,97.5),("shyam",20,87.65),("Azad",22,99.8)]
arr = np.array(values, dtype=names)
print(arr)
c = np.sort(arr)
print(f"the sorted array:\n{c}")
d = np.sort(arr, order = "age")
print(f"the sorted array using age:\n{c}")

[(b'ram', 21, 97.5 ) (b'shyam', 20, 87.65) (b'Azad', 22, 99.8 )]
the sorted array:
[(b'Azad', 22, 99.8 ) (b'ram', 21, 97.5 ) (b'shyam', 20, 87.65)]
the sorted array using age:
[(b'Azad', 22, 99.8 ) (b'ram', 21, 97.5 ) (b'shyam', 20, 87.65)]


In [62]:
#WHERE function
#* used for searching elements inside array
#* np.where(condition,[x,y])
#* if cond matches then element replaced by x ,if not then y
#* it will return indexes of elemets
#*if it 2d array then it gives (rows),(columns)
arr = np.array([1,2,3,1,2,3,4,5,6,7,8])
b= np.where(arr==2)
print(f"result which is equal to 2:\n{b}")
print(arr[b])
res =np.where(arr%2==0,"even","odd")
print(res)
res1 =np.where(arr%2==0,2,1)
print(res1)

result which is equal to 2:
(array([1, 4], dtype=int64),)
[2 2]
['odd' 'even' 'odd' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even']
[1 2 1 1 2 1 2 1 2 1 2]


In [86]:
# insert function
#*used to insert elements in an array
arr = np.array([10,20,30,40])
res = np.insert(arr, 1,99)
print(res)
#2d array
arr = np.array([[10,20],[30,40]])
print(arr)
res = np.insert(arr, 1,100, axis = 0)
print(res)
     

[10 99 20 30 40]
[[10 20]
 [30 40]]
[[ 10  20]
 [100 100]
 [ 30  40]]


In [59]:
#append function
a = np.array([10,20,30,40])
b = np.append(a,99)
print(b)
arr = np.array([[10,20],[30,40]])
b = np.append(arr,[[99,100]],axis =0)
print(b)

[10 20 30 40 99]
[[ 10  20]
 [ 30  40]
 [ 99 100]]


In [21]:
#delete function
import numpy as np
arr = np.array([1,2,3,4,5,6])
res = np.delete(arr, 4)# here 4 is the index no
print(f"after deletion is:\n{res}")

#2D array
#we use axis if we want to delete the portion of elements
a = np.arange(1,10).reshape(3,3)
print(f"the original array :\n{a}")
res = np.delete(a,1,axis = 0)
print(f"after deletion is:\n{res}")

#1d array
#if we want to delete portion of elements we use the range and sliceing
arr = np.array([1,2,3,4,5,6])
res = np.delete(arr, range(1,5))
res1 = np.delete(arr, np.s_[1:5])
print(f"after deletion is:\n{res}")
print(f"after deletion is:\n{res1}")


after deletion is:
[1 2 3 4 6]
the original array :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
after deletion is:
[[1 2 3]
 [7 8 9]]
after deletion is:
[1 6]
after deletion is:
[1 6]


In [31]:
#3D array
a = np.arange(1,61).reshape(3,4,5)
print(f"the original array:\n{a}")
res = np.delete(a,0,axis = 0)
print(f"after deletion is:\n{res}")

the original array:
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]
after deletion is:
[[[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]


In [35]:
a = np.arange(1,10).reshape(3,3)
print(a)
res = np.where(a%3==0,"*","#")
print(res)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[['#' '#' '*']
 ['#' '#' '*']
 ['#' '#' '*']]


In [61]:
a = np.arange(1,7).reshape(2,3)
print(f"the original array:\n{a}")
b = np.append(arr,[[99],[100]])
print(f"the extended arrayis:\n{b}")

the original array:
[[1 2 3]
 [4 5 6]]
the extended arrayis:
[ 10  20  30  40  99 100]


In [63]:
arr = np.arange(1,7)
print(f"array before shuffling:\n {arr}")
np.random.shuffle(arr)
print(f"array after shuffling:\n {arr}")

array before shuffling:
 [1 2 3 4 5 6]
array after shuffling:
 [5 2 3 4 1 6]


In [83]:
a = np.zeros((3,3))
print(a)
print(a+1)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
